# Generated by Django 2.0.4 on 2018-07-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_office', models.TextField(default='Office Location')),
                ('db_email', models.EmailField(default='example@parkitmy.com', max_length=254)),
                ('db_contact', models.CharField(default='0123456789', max_length=255)),
                ('first_name', models.CharField(default='first_name', max_length=255)),
                ('last_name', models.CharField(default='last_name', max_length=255)),
                ('db_longitude', models.CharField(default='Longitude', max_length=255)),
                ('db_latitude', models.CharField(default='Latitude', max_length=255)),
                ('db_location', models.CharField(default='Where?', max_length=100)),
                ('db_period', models.CharField(blank=True, max_length=100)),
                ('db_price', models.CharField(blank=True, max_length=100)),
                ('db_status', models.CharField(choices=[('New', 'New'), ('Done', 'Done'), ('WIP', 'WIP')], default='New', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
