# Generated by Django 2.0.4 on 2018-04-23 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
        ('search', '0002_remove_vehicle_parked_condo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='parked_condo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='condo_vehicle', to='rent.ParkingForRent'),
        ),
    ]
