# Generated by Django 2.0.4 on 2018-04-23 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_vehicle_parked_condo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='parked_condo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condo_vehicle', to='rent.ParkingForRent'),
        ),
    ]
