# Generated by Django 2.0.4 on 2018-07-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingforrent',
            name='db_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Enquiry', 'Enquiry'), ('Approved', 'Approved'), ('Occupied', 'Occupied')], default='Pending', max_length=100),
        ),
    ]
