# Generated by Django 2.0.4 on 2018-04-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingforrent',
            name='area',
            field=models.CharField(choices=[('KL_Sentral', 'KL Sentral'), ('Damansara', 'Damansara'), ('Other', 'Other')], default='Please Select Area', max_length=100),
        ),
        migrations.AlterField(
            model_name='parkingforrent',
            name='new_area',
            field=models.CharField(default=models.CharField(choices=[('KL_Sentral', 'KL Sentral'), ('Damansara', 'Damansara'), ('Other', 'Other')], default='Please Select Area', max_length=100), max_length=200, null=True),
        ),
    ]
