# Generated by Django 2.0.4 on 2018-05-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingforrent',
            name='db_type',
            field=models.CharField(choices=[('Condominium', 'Condominium'), ('Commercial', 'Commercial'), ('Landed', 'Landed')], default='Condominium', max_length=100),
        ),
    ]
