# Generated by Django 2.0.4 on 2018-04-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20180419_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingforrent',
            name='new_area',
            field=models.CharField(default=(('KL_Sentral', 'KL Sentral'), ('Damansara', 'Damansara'), ('Other', 'Other')), max_length=200, null=True),
        ),
    ]
