# Generated by Django 2.0.4 on 2018-04-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_auto_20180419_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingforrent',
            name='new_area',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
