# Generated by Django 2.0.4 on 2018-04-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_auto_20180419_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingforrent',
            name='new_price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parkingforrent',
            name='new_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
